version: '3.2'

# Создаем общую сеть проекта, для всех контейнеров
# Create a general project network for all containers
networks:
  laravel-network:
    driver: bridge
    external: true

services:
  mysql:
    container_name: laravel-test-mysql
    image: mysql:5.7
    # Подключаем к общей сети проекта с другими контейнерами
    # Connect to the general network of the project with other containers
    networks:
      - laravel-network
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    restart: always

  phpmyadmin:
    container_name: laravel-test-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - '58083:80'
    # Подключаем к общей сети проекта с другими контейнерами
    # Connect to the general network of the project with other containers
    networks:
      - laravel-network
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on:
      - mysql
    restart: always
